[profile.default]
solc_version = "0.8.22"
src = "contracts"
test = "test"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/"
]

[fuzz]
runs = 64
